# Generated by Django 4.2.1 on 2023-05-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('description', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.CharField(blank=True, max_length=99, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=99, null=True)),
                ('deadlink', models.DateTimeField(auto_now_add=True, max_length=99)),
                ('demand', models.TextField(max_length=221)),
                ('more_info', models.TextField(max_length=221)),
                ('workingtime', models.CharField(max_length=99)),
                ('call_time', models.CharField(max_length=99)),
                ('status', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djob.category')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('min_salary', models.CharField(blank=True, max_length=99, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=99, null=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('deadlink', models.DateTimeField(auto_now_add=True, max_length=99)),
                ('demand', models.TextField(max_length=221)),
                ('benefit', models.CharField(max_length=221)),
                ('location', models.IntegerField()),
                ('more_info', models.TextField(max_length=221)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'woman')], default=0)),
                ('workingtime', models.CharField(max_length=221)),
                ('call_time', models.CharField(max_length=221)),
                ('status', models.TextField(max_length=221)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djob.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
            ],
        ),
    ]
