# Generated by Django 4.2.1 on 2023-05-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=222)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(auto_created=True, blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=221, null=True)),
                ('lastname', models.CharField(blank=True, max_length=221, null=True)),
                ('middle_name', models.CharField(max_length=221)),
                ('username', models.CharField(blank=True, max_length=221, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.IntegerField()),
                ('number', models.CharField(blank=True, max_length=221, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, max_length=222, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.role')),
            ],
        ),
    ]
